dist: bionic

env:
  global:
    - CONFIGURATION=Release
    - VERSION_SUFFIX=aa-ci-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

language: csharp
mono: none
dotnet: 2.2

install:
- dotnet restore

script:
- dotnet build -c $CONFIGURATION --version-suffix $VERSION_SUFFIX
- dotnet test Fibonacci.Tests/Fibonacci.Tests.csproj

before_deploy:
  - on:
      branch: deploy-exp
    provider: script
    script:
      - 'bash --version && pwd && env'

#      - bash scripts/install_mono_and_nuget.sh

deploy:
  - on:
      branch: deploy-exp
    skip_cleanup: true
    provider: script
    script:
      - bash scripts/documentation_all.sh
